---

- name: Execute the Ansible Openstack demo tasks
  hosts: localhost
  vars_files:
    - vars/install-vars.yml
  tasks:
  - name: Create the test network
    os_network:
      auth:
         auth_url: "{{ os_auth }}"
         username: "{{ cloud_admin }}"
         password: "{{ admin_password }}"
         project_name: "{{ demo_project }}"
         project_domain_name: "{{ project_domain_name }}"
         user_domain_name: "{{ user_domain_name }}"
      state: present
      name: testnet1
      external: False
      shared: False
      wait: yes
    register: testnet_network

  - name: Create the test subnet
    os_subnet:
      auth:
         auth_url: "{{ os_auth }}"
         username: "{{ cloud_admin }}"
         password: "{{ admin_password }}"
         project_name: "{{ demo_project }}"
         project_domain_name: "{{ project_domain_name }}"
         user_domain_name: "{{ user_domain_name }}"
      state: present
      network_name: "{{ testnet_network.id }}"
      name: testnet_sub
      ip_version: 4
      cidr: 192.168.1.0/24
      gateway_ip: 192.168.1.1
      enable_dhcp: yes
      dns_nameservers:
        - 8.8.8.8
    register: testnet_sub

  - name: Create the test router
    ignore_errors: yes #for some reasons, re-running this task gives errors
    os_router:
      auth:
         auth_url: "{{ os_auth }}"
         username: "{{ cloud_admin }}"
         password: "{{ admin_password }}"
         project_name: "{{ demo_project }}"
         project_domain_name: "{{ project_domain_name }}"
         user_domain_name: "{{ user_domain_name }}"
      region_name: "{{ region_name }}"
      enable_snat: yes
      state: present
      name: testnet_router
      network: "{{ ext_net }}"
      interfaces:
        - testnet_sub

  - name: Create test port
    os_port:
      auth:
        auth_url: "{{ os_auth }}"
        username: "{{ cloud_admin }}"
        password: "{{ admin_password }}"
        project_name: "{{ demo_project }}"
        project_domain_name: "{{ project_domain_name }}"
        user_domain_name: "{{ user_domain_name }}"
      state: present
      name: "{{ test_port }}"
      network: "{{ testnet_network.id }}"
      # network: testnet
      security_groups: "{{ sec_group }}"
    register: testport_port

  # - name: Create a new security group
  #   os_security_group:
  #     state: present
  #     name: secgr
  
  # - name: Create a new security group allowing any ICMP
  #   os_security_group_rule:
  #     security_group: secgr
  #     protocol: icmp
  #     remote_ip_prefix: 0.0.0.0/0

  # - name: Create a new security group allowing any SSH connection
  #   os_security_group_rule:
  #     security_group: secgr
  #     protocol: tcp
  #     port_range_min: 22
  #     port_range_max: 22
  #     remote_ip_prefix: 0.0.0.0/0

  - name: Create server instance
    os_server:
      auth:
         auth_url: "{{ os_auth }}"
         username: "{{ cloud_admin }}"
         password: "{{ admin_password }}"
         project_name: "{{ demo_project }}"
         project_domain_name: "{{ project_domain_name }}"
         user_domain_name: "{{ user_domain_name }}"
      state: present
      name: "{{ test_server }}"
      image: rhel7_ocp
      flavor: medium
      security_groups: default
      key_name: key1
      nics:
        # - net-id: "{{ testnet_network.id }}"
        #- net-id: a39b8f6c-cba2-493e-a777-eed61cabf70a
        - port-id: "{{ testport_port.id }}"
      auto_ip: yes
      userdata: |
        #cloud-config
        user: demouser
        password: demouser
        chpasswd: {expire: False}

        runcmd:
         - tee -a /usr/local/bin/mhatds.sh <<< "#!/bin/bash"
         - tee -a /usr/local/bin/mhatds.sh <<< "echo 'This is a sample script to test auto run during boot' >> /var/log/script.out"
         - tee -a /usr/local/bin/mhatds.sh <<< "echo 'The time the script run was -->  `date`' >> /var/log/script.out"
         - chmod +x /usr/local/bin/mhatds.sh

         - tee -a /etc/systemd/system/mhatds.service <<< "[Unit]"
         - tee -a /etc/systemd/system/mhatds.service <<< "Description=Description for sample script goes here"
         - tee -a /etc/systemd/system/mhatds.service <<< "After=network.target"
         - tee -a /etc/systemd/system/mhatds.service <<< "[Service]"
         - tee -a /etc/systemd/system/mhatds.service <<< "Type=idle"
         - tee -a /etc/systemd/system/mhatds.service <<< "ExecStart=/usr/local/bin/mhatds.sh"
         - tee -a /etc/systemd/system/mhatds.service <<< "TimeoutStartSec=0"
         - tee -a /etc/systemd/system/mhatds.service <<< "[Install]"
         - tee -a /etc/systemd/system/mhatds.service <<< "WantedBy=multi-user.target"

         - systemctl daemon-reload
         - systemctl enable mhatds.service
         - systemctl start mhatds.service
         - shutdown -r
    register: testServer

  - name: Show Server's IP
    debug: var=testServer.openstack.public_v4
